CREATE TABLE AI_MCP_TOOL_CHANNEL_BLOCK (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    MCP_SERVER_NAME VARCHAR2(128),
    TOOL_NAME VARCHAR2(128) NOT NULL,
    CHANNEL_CODE VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(16) NOT NULL,
    MESSAGE VARCHAR2(256),
    IS_DELETE VARCHAR2(1) NOT NULL,
    EFFECTIVE_FROM VARCHAR2(20),
    EFFECTIVE_TO VARCHAR2(20),
    INPUT_ID VARCHAR2(10),
    INPUT_TIME VARCHAR2(20),
    INPUT_ORG VARCHAR2(10),
    UPDATE_ID VARCHAR2(10),
    UPDATE_TIME VARCHAR2(20),
    UPDATE_ORG VARCHAR2(10)
);

CREATE UNIQUE INDEX UK_MCP_TOOL_CHANNEL_BLOCK
    ON AI_MCP_TOOL_CHANNEL_BLOCK (MCP_SERVER_NAME, TOOL_NAME, CHANNEL_CODE);

CREATE INDEX IDX_MCP_TOOL_CHANNEL_BLOCK
    ON AI_MCP_TOOL_CHANNEL_BLOCK (TOOL_NAME, CHANNEL_CODE, STATUS, IS_DELETE);
