-- Oracle 12c+：Agent-Skill 动态版本绑定表
CREATE TABLE agent_skill_binding (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name       VARCHAR2(128 CHAR)  NOT NULL,
    skill_name       VARCHAR2(128 CHAR)  NOT NULL,
    skill_version    VARCHAR2(64 CHAR)   NOT NULL,
    skill_file_path  VARCHAR2(1024 CHAR) NOT NULL,
    enabled          NUMBER(1) DEFAULT 1 NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_agent_skill UNIQUE (agent_name, skill_name),
    CONSTRAINT ck_agent_skill_enabled CHECK (enabled IN (0, 1))
);

CREATE INDEX idx_agent_skill_enabled
    ON agent_skill_binding(agent_name, enabled);
