-- ============================================================
-- H2 Schema：Agent 治理配置表
-- ★ 使用 H2 标准语法，列名与 Oracle 版本一致
-- ============================================================

CREATE TABLE IF NOT EXISTS agent_governance_config (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_type      VARCHAR(8)   NOT NULL,
    agent_name       VARCHAR(128),
    status           VARCHAR(16)  DEFAULT 'DISABLED',
    default_status   VARCHAR(16)  DEFAULT 'DISABLED',
    user_id          VARCHAR(64),
    org_id           VARCHAR(64),
    effective_from   TIMESTAMP    NULL,
    effective_to     TIMESTAMP    NULL,
    path_pattern     VARCHAR(256),
    is_stream        TINYINT      DEFAULT 0,
    description      VARCHAR(512),
    created_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_gov_agent_name ON agent_governance_config(agent_name);
CREATE INDEX IF NOT EXISTS idx_gov_user_id    ON agent_governance_config(user_id);
CREATE INDEX IF NOT EXISTS idx_gov_org_id     ON agent_governance_config(org_id);

-- ============================================================
-- Agent-Skill 动态版本绑定
-- ============================================================

CREATE TABLE IF NOT EXISTS agent_skill_binding (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name       VARCHAR(128)  NOT NULL,
    skill_name       VARCHAR(128)  NOT NULL,
    skill_version    VARCHAR(64)   NOT NULL,
    skill_file_path  VARCHAR(1024) NOT NULL,
    enabled          BOOLEAN       DEFAULT TRUE NOT NULL,
    created_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_agent_skill UNIQUE (agent_name, skill_name)
);

CREATE INDEX IF NOT EXISTS idx_agent_skill_enabled
    ON agent_skill_binding(agent_name, enabled);
