CREATE TABLE IF NOT EXISTS AI_MODEL (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    MODEL_ID VARCHAR2(32) NOT NULL UNIQUE,
    STATUS VARCHAR2(16) NOT NULL,
    PROVIDER_CODE VARCHAR2(64) NOT NULL,
    MODEL_NAME VARCHAR2(128) NOT NULL,
    ENDPOINT_URI VARCHAR2(1000) NOT NULL,
    CREDENTIAL_REF VARCHAR2(256) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT CK_AI_MODEL_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT CK_AI_MODEL_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

CREATE TABLE IF NOT EXISTS AI_AGENT (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    AGENT_ID VARCHAR2(32) NOT NULL UNIQUE,
    AGENT_NAME VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(16) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT CK_AI_AGENT_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT CK_AI_AGENT_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

CREATE TABLE IF NOT EXISTS AI_SKILL (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    SKILL_ID VARCHAR2(32) NOT NULL UNIQUE,
    SKILL_CODE VARCHAR2(64) NOT NULL UNIQUE,
    STATUS VARCHAR2(10) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT CK_AI_SKILL_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT CK_AI_SKILL_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

CREATE TABLE IF NOT EXISTS AI_AGENT_NODE (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    NODE_ID VARCHAR2(32) NOT NULL UNIQUE,
    AGENT_ID VARCHAR2(32) NOT NULL,
    NODE_SYSTEM_PROMPT CLOB NOT NULL,
    NODE_USER_PROMPT CLOB,
    MODEL_ID VARCHAR2(32) NOT NULL,
    TEMPERATURE NUMBER(20, 2),
    MAX_TOKEN NUMBER(20),
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT FK_NODE_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES AI_AGENT (AGENT_ID),
    CONSTRAINT FK_NODE_MODEL FOREIGN KEY (MODEL_ID)
        REFERENCES AI_MODEL (MODEL_ID),
    CONSTRAINT CK_AI_NODE_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

CREATE TABLE IF NOT EXISTS AI_AGENT_NODE_SKILL_BINDING (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    NODE_ID VARCHAR2(32) NOT NULL,
    SKILL_ID VARCHAR2(32) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_NODE_SKILL UNIQUE (NODE_ID, SKILL_ID),
    CONSTRAINT FK_BIND_NODE FOREIGN KEY (NODE_ID)
        REFERENCES AI_AGENT_NODE (NODE_ID),
    CONSTRAINT FK_BIND_SKILL FOREIGN KEY (SKILL_ID)
        REFERENCES AI_SKILL (SKILL_ID),
    CONSTRAINT CK_NODE_SKILL_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

CREATE TABLE IF NOT EXISTS AI_TOOL (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    TOOL_ID VARCHAR2(32) NOT NULL UNIQUE,
    MCP_CODE VARCHAR2(64) NOT NULL,
    TOOL_CODE VARCHAR2(128) NOT NULL,
    TOOL_NAME VARCHAR2(128) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_MCP_TOOL UNIQUE (MCP_CODE, TOOL_CODE),
    CONSTRAINT CK_AI_TOOL_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

CREATE TABLE IF NOT EXISTS AI_TOOL_BINDING (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    BINDING_ID VARCHAR2(32) NOT NULL,
    BINDING_TYPE VARCHAR2(10) NOT NULL,
    TOOL_ID VARCHAR2(32) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_TOOL_BINDING UNIQUE (BINDING_ID, BINDING_TYPE, TOOL_ID),
    CONSTRAINT FK_TB_TOOL FOREIGN KEY (TOOL_ID)
        REFERENCES AI_TOOL (TOOL_ID),
    CONSTRAINT CK_TOOL_BINDING_TYPE CHECK (BINDING_TYPE IN ('SKILL', 'AGENT_NODE')),
    CONSTRAINT CK_TOOL_BINDING_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

CREATE TABLE IF NOT EXISTS AI_CALL_AUDIT_LOG (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    TRACE_ID VARCHAR2(64),
    SPAN_ID VARCHAR2(32),
    CALL_TYPE VARCHAR2(10) NOT NULL,
    AGENT_ID VARCHAR2(32),
    NODE_ID VARCHAR2(32),
    CALL_NAME VARCHAR2(128) NOT NULL,
    INPUT_TEXT CLOB,
    OUTPUT_TEXT CLOB,
    SUCCESS VARCHAR2(1) NOT NULL,
    ERROR_MESSAGE CLOB,
    DURATION_MS NUMBER(20) NOT NULL,
    CREATE_TIME VARCHAR2(24) NOT NULL,
    CONSTRAINT CK_CALL_AUDIT_TYPE CHECK (CALL_TYPE IN ('MODEL', 'TOOL')),
    CONSTRAINT CK_CALL_AUDIT_SUCCESS CHECK (SUCCESS IN ('0', '1'))
);

CREATE TABLE IF NOT EXISTS AI_MCP_TOOL_CALL_LOG (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    TRACE_ID VARCHAR2(64),
    SPAN_ID VARCHAR2(32),
    MCP_SERVER_NAME VARCHAR2(128) NOT NULL,
    MCP_ENDPOINT VARCHAR2(256) NOT NULL,
    TOOL_NAME VARCHAR2(128) NOT NULL,
    TOOL_INPUT CLOB,
    TOOL_OUTPUT CLOB,
    SUCCESS VARCHAR2(1) NOT NULL,
    ERROR_MESSAGE CLOB,
    DURATION_MS NUMBER(20) NOT NULL,
    CREATE_TIME VARCHAR2(24) NOT NULL,
    CONSTRAINT CK_MCP_TOOL_CALL_SUCCESS CHECK (SUCCESS IN ('0', '1'))
);

CREATE TABLE IF NOT EXISTS AI_MCP_TOOL_CHANNEL_BLOCK (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    MCP_SERVER_NAME VARCHAR2(128),
    TOOL_NAME VARCHAR2(128) NOT NULL,
    CHANNEL_CODE VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(16) NOT NULL,
    MESSAGE VARCHAR2(512),
    IS_DELETE VARCHAR2(1) NOT NULL,
    EFFECTIVE_FROM VARCHAR2(24),
    EFFECTIVE_TO VARCHAR2(24),
    CONSTRAINT CK_MCP_TOOL_CHANNEL_BLOCK_STATUS
        CHECK (STATUS IN ('ENABLED', 'DISABLED')),
    CONSTRAINT CK_MCP_TOOL_CHANNEL_BLOCK_DELETE
        CHECK (IS_DELETE IN ('0', '1')),
    CONSTRAINT UK_MCP_TOOL_CHANNEL_BLOCK
        UNIQUE (MCP_SERVER_NAME, TOOL_NAME, CHANNEL_CODE)
);

CREATE INDEX IF NOT EXISTS IDX_NODE_AGENT ON AI_AGENT_NODE (AGENT_ID);
CREATE INDEX IF NOT EXISTS IDX_BIND_NODE
    ON AI_AGENT_NODE_SKILL_BINDING (NODE_ID);
CREATE INDEX IF NOT EXISTS IDX_TOOL_BINDING_TARGET
    ON AI_TOOL_BINDING (BINDING_TYPE, BINDING_ID);
CREATE INDEX IF NOT EXISTS IDX_CALL_AUDIT_TRACE
    ON AI_CALL_AUDIT_LOG (TRACE_ID);
CREATE INDEX IF NOT EXISTS IDX_CALL_AUDIT_TIME
    ON AI_CALL_AUDIT_LOG (CREATE_TIME);
CREATE INDEX IF NOT EXISTS IDX_MCP_TOOL_CALL_TRACE
    ON AI_MCP_TOOL_CALL_LOG (TRACE_ID);
CREATE INDEX IF NOT EXISTS IDX_MCP_TOOL_CALL_TIME
    ON AI_MCP_TOOL_CALL_LOG (CREATE_TIME);
CREATE INDEX IF NOT EXISTS IDX_MCP_TOOL_CALL_TOOL
    ON AI_MCP_TOOL_CALL_LOG (TOOL_NAME);
CREATE INDEX IF NOT EXISTS IDX_MCP_TOOL_CHANNEL_BLOCK
    ON AI_MCP_TOOL_CHANNEL_BLOCK (TOOL_NAME, CHANNEL_CODE, STATUS, IS_DELETE);
