MERGE INTO AI_MODEL t
USING (
    SELECT
        '00000000000000000000000000000001' AS PK_ID,
        'deepseek-main' AS MODEL_ID,
        'PUBLISHED' AS STATUS,
        'deepseek' AS PROVIDER_CODE,
        'deepseek-chat' AS MODEL_NAME,
        'https://api.deepseek.com' AS ENDPOINT_URI,
        'replace-with-real-deepseek-api-key' AS CREDENTIAL_REF,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, MODEL_ID, STATUS, PROVIDER_CODE, MODEL_NAME, ENDPOINT_URI,
    CREDENTIAL_REF, IS_DELETE, INPUT_ID, INPUT_TIME, INPUT_ORG,
    UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.MODEL_ID, s.STATUS, s.PROVIDER_CODE, s.MODEL_NAME,
    s.ENDPOINT_URI, s.CREDENTIAL_REF, s.IS_DELETE, s.INPUT_ID,
    s.INPUT_TIME, s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME, s.UPDATE_ORG
);

MERGE INTO AI_AGENT t
USING (
    SELECT
        '00000000000000000000000000000002' AS PK_ID,
        'credit-agent' AS AGENT_ID,
        '征信与天气助手' AS AGENT_NAME,
        'PUBLISHED' AS STATUS,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, AGENT_ID, AGENT_NAME, STATUS, IS_DELETE,
    INPUT_ID, INPUT_TIME, INPUT_ORG, UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.AGENT_ID, s.AGENT_NAME, s.STATUS, s.IS_DELETE,
    s.INPUT_ID, s.INPUT_TIME, s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME,
    s.UPDATE_ORG
);

MERGE INTO AI_SKILL t
USING (
    SELECT
        '00000000000000000000000000000003' AS PK_ID,
        'skill-credit' AS SKILL_ID,
        'enterprise-credit-query' AS SKILL_CODE,
        'PUBLISHED' AS STATUS,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, SKILL_ID, SKILL_CODE, STATUS, IS_DELETE,
    INPUT_ID, INPUT_TIME, INPUT_ORG, UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.SKILL_ID, s.SKILL_CODE, s.STATUS, s.IS_DELETE,
    s.INPUT_ID, s.INPUT_TIME, s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME,
    s.UPDATE_ORG
);

MERGE INTO AI_SKILL t
USING (
    SELECT
        '00000000000000000000000000000004' AS PK_ID,
        'skill-weather' AS SKILL_ID,
        'local-weather-query' AS SKILL_CODE,
        'PUBLISHED' AS STATUS,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, SKILL_ID, SKILL_CODE, STATUS, IS_DELETE,
    INPUT_ID, INPUT_TIME, INPUT_ORG, UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.SKILL_ID, s.SKILL_CODE, s.STATUS, s.IS_DELETE,
    s.INPUT_ID, s.INPUT_TIME, s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME,
    s.UPDATE_ORG
);

MERGE INTO AI_AGENT_NODE t
USING (
    SELECT
        '00000000000000000000000000000005' AS PK_ID,
        'credit-agent-node' AS NODE_ID,
        'credit-agent' AS AGENT_ID,
        'classpath:prompt/system-prompt.md' AS NODE_SYSTEM_PROMPT,
        '' AS NODE_USER_PROMPT,
        'deepseek-main' AS MODEL_ID,
        0.20 AS TEMPERATURE,
        2048 AS MAX_TOKEN,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, NODE_ID, AGENT_ID, NODE_SYSTEM_PROMPT, NODE_USER_PROMPT,
    MODEL_ID, TEMPERATURE, MAX_TOKEN, IS_DELETE, INPUT_ID, INPUT_TIME,
    INPUT_ORG, UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.NODE_ID, s.AGENT_ID, s.NODE_SYSTEM_PROMPT, s.NODE_USER_PROMPT,
    s.MODEL_ID, s.TEMPERATURE, s.MAX_TOKEN, s.IS_DELETE, s.INPUT_ID,
    s.INPUT_TIME, s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME, s.UPDATE_ORG
);

MERGE INTO AI_AGENT_NODE_SKILL_BINDING t
USING (
    SELECT
        '00000000000000000000000000000006' AS PK_ID,
        'credit-agent-node' AS NODE_ID,
        'skill-credit' AS SKILL_ID,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, NODE_ID, SKILL_ID, IS_DELETE, INPUT_ID, INPUT_TIME, INPUT_ORG,
    UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.NODE_ID, s.SKILL_ID, s.IS_DELETE, s.INPUT_ID, s.INPUT_TIME,
    s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME, s.UPDATE_ORG
);

MERGE INTO AI_AGENT_NODE_SKILL_BINDING t
USING (
    SELECT
        '00000000000000000000000000000007' AS PK_ID,
        'credit-agent-node' AS NODE_ID,
        'skill-weather' AS SKILL_ID,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, NODE_ID, SKILL_ID, IS_DELETE, INPUT_ID, INPUT_TIME, INPUT_ORG,
    UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.NODE_ID, s.SKILL_ID, s.IS_DELETE, s.INPUT_ID, s.INPUT_TIME,
    s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME, s.UPDATE_ORG
);

MERGE INTO AI_TOOL t
USING (
    SELECT
        '00000000000000000000000000000008' AS PK_ID,
        'tool-credit' AS TOOL_ID,
        'nacos-mcp-agent' AS MCP_CODE,
        'queryEnterpriseCredit' AS TOOL_CODE,
        '企业征信查询' AS TOOL_NAME,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, TOOL_ID, MCP_CODE, TOOL_CODE, TOOL_NAME, IS_DELETE,
    INPUT_ID, INPUT_TIME, INPUT_ORG, UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.TOOL_ID, s.MCP_CODE, s.TOOL_CODE, s.TOOL_NAME, s.IS_DELETE,
    s.INPUT_ID, s.INPUT_TIME, s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME,
    s.UPDATE_ORG
);

MERGE INTO AI_TOOL t
USING (
    SELECT
        '00000000000000000000000000000009' AS PK_ID,
        'tool-weather' AS TOOL_ID,
        'nacos-mcp-agent' AS MCP_CODE,
        'getWeatherByCity' AS TOOL_CODE,
        '城市天气查询' AS TOOL_NAME,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, TOOL_ID, MCP_CODE, TOOL_CODE, TOOL_NAME, IS_DELETE,
    INPUT_ID, INPUT_TIME, INPUT_ORG, UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.TOOL_ID, s.MCP_CODE, s.TOOL_CODE, s.TOOL_NAME, s.IS_DELETE,
    s.INPUT_ID, s.INPUT_TIME, s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME,
    s.UPDATE_ORG
);

MERGE INTO AI_TOOL_BINDING t
USING (
    SELECT
        '00000000000000000000000000000010' AS PK_ID,
        'skill-credit' AS BINDING_ID,
        'SKILL' AS BINDING_TYPE,
        'tool-credit' AS TOOL_ID,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, BINDING_ID, BINDING_TYPE, TOOL_ID, IS_DELETE, INPUT_ID,
    INPUT_TIME, INPUT_ORG, UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.BINDING_ID, s.BINDING_TYPE, s.TOOL_ID, s.IS_DELETE,
    s.INPUT_ID, s.INPUT_TIME, s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME,
    s.UPDATE_ORG
);

MERGE INTO AI_TOOL_BINDING t
USING (
    SELECT
        '00000000000000000000000000000011' AS PK_ID,
        'skill-weather' AS BINDING_ID,
        'SKILL' AS BINDING_TYPE,
        'tool-weather' AS TOOL_ID,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, BINDING_ID, BINDING_TYPE, TOOL_ID, IS_DELETE, INPUT_ID,
    INPUT_TIME, INPUT_ORG, UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.BINDING_ID, s.BINDING_TYPE, s.TOOL_ID, s.IS_DELETE,
    s.INPUT_ID, s.INPUT_TIME, s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME,
    s.UPDATE_ORG
);

MERGE INTO AI_TOOL_BINDING t
USING (
    SELECT
        '00000000000000000000000000000012' AS PK_ID,
        'credit-agent-node' AS BINDING_ID,
        'AGENT_NODE' AS BINDING_TYPE,
        'tool-weather' AS TOOL_ID,
        '0' AS IS_DELETE,
        'system' AS INPUT_ID,
        '2026-07-20 00:00:00' AS INPUT_TIME,
        '0000000000' AS INPUT_ORG,
        'system' AS UPDATE_ID,
        '2026-07-20 00:00:00' AS UPDATE_TIME,
        '0000000000' AS UPDATE_ORG
    FROM DUAL
) s
ON (t.PK_ID = s.PK_ID)
WHEN NOT MATCHED THEN INSERT (
    PK_ID, BINDING_ID, BINDING_TYPE, TOOL_ID, IS_DELETE, INPUT_ID,
    INPUT_TIME, INPUT_ORG, UPDATE_ID, UPDATE_TIME, UPDATE_ORG
) VALUES (
    s.PK_ID, s.BINDING_ID, s.BINDING_TYPE, s.TOOL_ID, s.IS_DELETE,
    s.INPUT_ID, s.INPUT_TIME, s.INPUT_ORG, s.UPDATE_ID, s.UPDATE_TIME,
    s.UPDATE_ORG
);

COMMIT;
