CREATE TABLE AI_MODEL (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    MODEL_ID VARCHAR2(32) NOT NULL,
    STATUS VARCHAR2(16) NOT NULL,
    PROVIDER_CODE VARCHAR2(64) NOT NULL,
    MODEL_NAME VARCHAR2(128) NOT NULL,
    ENDPOINT_URI VARCHAR2(1000),
    CREDENTIAL_REF VARCHAR2(256),
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_AI_MODEL_ID UNIQUE (MODEL_ID),
    CONSTRAINT CK_AI_MODEL_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT CK_AI_MODEL_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

COMMENT ON TABLE AI_MODEL IS '模型表';
COMMENT ON COLUMN AI_MODEL.PK_ID IS '技术主键';
COMMENT ON COLUMN AI_MODEL.MODEL_ID IS '模型表业务主键';
COMMENT ON COLUMN AI_MODEL.STATUS IS '模型表状态';
COMMENT ON COLUMN AI_MODEL.PROVIDER_CODE IS '模型提供方';
COMMENT ON COLUMN AI_MODEL.MODEL_NAME IS '提供方实际模型名称';
COMMENT ON COLUMN AI_MODEL.ENDPOINT_URI IS '可选兼容 API 地址';
COMMENT ON COLUMN AI_MODEL.CREDENTIAL_REF IS '凭证';
COMMENT ON COLUMN AI_MODEL.IS_DELETE IS '逻辑删除标记';
COMMENT ON COLUMN AI_MODEL.INPUT_ID IS '创建人 ID';
COMMENT ON COLUMN AI_MODEL.INPUT_TIME IS '创建时间';
COMMENT ON COLUMN AI_MODEL.INPUT_ORG IS '创建机构';
COMMENT ON COLUMN AI_MODEL.UPDATE_ID IS '最后更新人 ID';
COMMENT ON COLUMN AI_MODEL.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN AI_MODEL.UPDATE_ORG IS '最后更新机构';

CREATE TABLE AI_AGENT (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    AGENT_ID VARCHAR2(32) NOT NULL,
    AGENT_NAME VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(16) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_AI_AGENT_ID UNIQUE (AGENT_ID),
    CONSTRAINT CK_AI_AGENT_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT CK_AI_AGENT_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

COMMENT ON TABLE AI_AGENT IS 'Agent 表';
COMMENT ON COLUMN AI_AGENT.PK_ID IS '技术主键';
COMMENT ON COLUMN AI_AGENT.AGENT_ID IS 'Agent主键';
COMMENT ON COLUMN AI_AGENT.AGENT_NAME IS 'Agent 展示名称';
COMMENT ON COLUMN AI_AGENT.STATUS IS 'Agent 版本状态';
COMMENT ON COLUMN AI_AGENT.IS_DELETE IS '逻辑删除标记';
COMMENT ON COLUMN AI_AGENT.INPUT_ID IS '创建人 ID';
COMMENT ON COLUMN AI_AGENT.INPUT_TIME IS '创建时间';
COMMENT ON COLUMN AI_AGENT.INPUT_ORG IS '创建机构';
COMMENT ON COLUMN AI_AGENT.UPDATE_ID IS '最后更新人 ID';
COMMENT ON COLUMN AI_AGENT.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN AI_AGENT.UPDATE_ORG IS '最后更新机构';

CREATE TABLE AI_SKILL (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    SKILL_ID VARCHAR2(32) NOT NULL,
    SKILL_CODE VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(10) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_AI_SKILL_ID UNIQUE (SKILL_ID),
    CONSTRAINT UK_AI_SKILL_CODE UNIQUE (SKILL_CODE),
    CONSTRAINT CK_AI_SKILL_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT CK_AI_SKILL_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

COMMENT ON TABLE AI_SKILL IS 'Skill 表';
COMMENT ON COLUMN AI_SKILL.PK_ID IS '技术主键';
COMMENT ON COLUMN AI_SKILL.SKILL_ID IS 'Skill主键';
COMMENT ON COLUMN AI_SKILL.SKILL_CODE IS 'SKILL_CODE';
COMMENT ON COLUMN AI_SKILL.STATUS IS 'Skill状态';
COMMENT ON COLUMN AI_SKILL.IS_DELETE IS '逻辑删除标记';
COMMENT ON COLUMN AI_SKILL.INPUT_ID IS '创建人 ID';
COMMENT ON COLUMN AI_SKILL.INPUT_TIME IS '创建时间';
COMMENT ON COLUMN AI_SKILL.INPUT_ORG IS '创建机构';
COMMENT ON COLUMN AI_SKILL.UPDATE_ID IS '最后更新人 ID';
COMMENT ON COLUMN AI_SKILL.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN AI_SKILL.UPDATE_ORG IS '最后更新机构';

CREATE TABLE AI_AGENT_NODE (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    NODE_ID VARCHAR2(32) NOT NULL,
    AGENT_ID VARCHAR2(32) NOT NULL,
    NODE_SYSTEM_PROMPT CLOB,
    NODE_USER_PROMPT CLOB,
    MODEL_ID VARCHAR2(32),
    TEMPERATURE NUMBER(20,2),
    MAX_TOKEN NUMBER(20),
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_AI_AGENT_NODE_ID UNIQUE (NODE_ID),
    CONSTRAINT FK_NODE_AGENT FOREIGN KEY (AGENT_ID)
        REFERENCES AI_AGENT (AGENT_ID),
    CONSTRAINT FK_NODE_MODEL FOREIGN KEY (MODEL_ID)
        REFERENCES AI_MODEL (MODEL_ID),
    CONSTRAINT CK_AI_NODE_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

COMMENT ON TABLE AI_AGENT_NODE IS 'Agent 节点表';
COMMENT ON COLUMN AI_AGENT_NODE.PK_ID IS '技术主键';
COMMENT ON COLUMN AI_AGENT_NODE.NODE_ID IS '节点主键';
COMMENT ON COLUMN AI_AGENT_NODE.AGENT_ID IS '所属 Agentid';
COMMENT ON COLUMN AI_AGENT_NODE.NODE_SYSTEM_PROMPT IS '节点级系统提示词';
COMMENT ON COLUMN AI_AGENT_NODE.NODE_USER_PROMPT IS '节点级用户提示词';
COMMENT ON COLUMN AI_AGENT_NODE.MODEL_ID IS '节点引用的模型版本';
COMMENT ON COLUMN AI_AGENT_NODE.TEMPERATURE IS '温度';
COMMENT ON COLUMN AI_AGENT_NODE.MAX_TOKEN IS '最大token数';
COMMENT ON COLUMN AI_AGENT_NODE.IS_DELETE IS '逻辑删除标记';
COMMENT ON COLUMN AI_AGENT_NODE.INPUT_ID IS '创建人 ID';
COMMENT ON COLUMN AI_AGENT_NODE.INPUT_TIME IS '创建时间';
COMMENT ON COLUMN AI_AGENT_NODE.INPUT_ORG IS '创建机构';
COMMENT ON COLUMN AI_AGENT_NODE.UPDATE_ID IS '最后更新人 ID';
COMMENT ON COLUMN AI_AGENT_NODE.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN AI_AGENT_NODE.UPDATE_ORG IS '最后更新机构';

CREATE TABLE AI_AGENT_NODE_SKILL_BINDING (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    NODE_ID VARCHAR2(32) NOT NULL,
    SKILL_ID VARCHAR2(32) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_NODE_SKILL UNIQUE (NODE_ID, SKILL_ID),
    CONSTRAINT FK_BIND_NODE FOREIGN KEY (NODE_ID)
        REFERENCES AI_AGENT_NODE (NODE_ID),
    CONSTRAINT FK_BIND_SKILL FOREIGN KEY (SKILL_ID)
        REFERENCES AI_SKILL (SKILL_ID),
    CONSTRAINT CK_NODE_SKILL_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

COMMENT ON TABLE AI_AGENT_NODE_SKILL_BINDING IS 'Agent 节点技能绑定表';
COMMENT ON COLUMN AI_AGENT_NODE_SKILL_BINDING.PK_ID IS '技术主键';
COMMENT ON COLUMN AI_AGENT_NODE_SKILL_BINDING.NODE_ID IS '绑定的 Agent 节点';
COMMENT ON COLUMN AI_AGENT_NODE_SKILL_BINDING.SKILL_ID IS '绑定的 Skill 版本';
COMMENT ON COLUMN AI_AGENT_NODE_SKILL_BINDING.IS_DELETE IS '逻辑删除标记';
COMMENT ON COLUMN AI_AGENT_NODE_SKILL_BINDING.INPUT_ID IS '创建人 ID';
COMMENT ON COLUMN AI_AGENT_NODE_SKILL_BINDING.INPUT_TIME IS '创建时间';
COMMENT ON COLUMN AI_AGENT_NODE_SKILL_BINDING.INPUT_ORG IS '创建机构';
COMMENT ON COLUMN AI_AGENT_NODE_SKILL_BINDING.UPDATE_ID IS '最后更新人 ID';
COMMENT ON COLUMN AI_AGENT_NODE_SKILL_BINDING.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN AI_AGENT_NODE_SKILL_BINDING.UPDATE_ORG IS '最后更新机构';

CREATE TABLE AI_TOOL (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    TOOL_ID VARCHAR2(32) NOT NULL,
    MCP_CODE VARCHAR2(64) NOT NULL,
    TOOL_CODE VARCHAR2(128) NOT NULL,
    TOOL_NAME VARCHAR2(128) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_AI_TOOL_ID UNIQUE (TOOL_ID),
    CONSTRAINT UK_MCP_TOOL UNIQUE (MCP_CODE, TOOL_CODE),
    CONSTRAINT CK_AI_TOOL_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

COMMENT ON TABLE AI_TOOL IS '工具表';
COMMENT ON COLUMN AI_TOOL.PK_ID IS '技术主键';
COMMENT ON COLUMN AI_TOOL.TOOL_ID IS '工具业务主键';
COMMENT ON COLUMN AI_TOOL.MCP_CODE IS 'MCP编码';
COMMENT ON COLUMN AI_TOOL.TOOL_CODE IS '工具名称，用于从注册的所有工具进行筛选';
COMMENT ON COLUMN AI_TOOL.TOOL_NAME IS '工具展示名称';
COMMENT ON COLUMN AI_TOOL.IS_DELETE IS '逻辑删除标记';
COMMENT ON COLUMN AI_TOOL.INPUT_ID IS '创建人 ID';
COMMENT ON COLUMN AI_TOOL.INPUT_TIME IS '创建时间';
COMMENT ON COLUMN AI_TOOL.INPUT_ORG IS '创建机构';
COMMENT ON COLUMN AI_TOOL.UPDATE_ID IS '最后更新人 ID';
COMMENT ON COLUMN AI_TOOL.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN AI_TOOL.UPDATE_ORG IS '最后更新机构';

CREATE TABLE AI_TOOL_BINDING (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    BINDING_ID VARCHAR2(32) NOT NULL,
    BINDING_TYPE VARCHAR2(10) NOT NULL,
    TOOL_ID VARCHAR2(32) NOT NULL,
    IS_DELETE VARCHAR2(1) NOT NULL,
    INPUT_ID VARCHAR2(10) NOT NULL,
    INPUT_TIME VARCHAR2(20) NOT NULL,
    INPUT_ORG VARCHAR2(10) NOT NULL,
    UPDATE_ID VARCHAR2(10) NOT NULL,
    UPDATE_TIME VARCHAR2(20) NOT NULL,
    UPDATE_ORG VARCHAR2(10) NOT NULL,
    CONSTRAINT UK_TOOL_BINDING UNIQUE (BINDING_ID, BINDING_TYPE, TOOL_ID),
    CONSTRAINT FK_TB_TOOL FOREIGN KEY (TOOL_ID)
        REFERENCES AI_TOOL (TOOL_ID),
    CONSTRAINT CK_TOOL_BINDING_TYPE CHECK (BINDING_TYPE IN ('SKILL', 'AGENT_NODE')),
    CONSTRAINT CK_TOOL_BINDING_DELETE CHECK (IS_DELETE IN ('0', '1'))
);

COMMENT ON TABLE AI_TOOL_BINDING IS '工具绑定表';
COMMENT ON COLUMN AI_TOOL_BINDING.PK_ID IS '技术主键';
COMMENT ON COLUMN AI_TOOL_BINDING.BINDING_ID IS '绑定的 SkillIID或者AgentID（联合业务主键）';
COMMENT ON COLUMN AI_TOOL_BINDING.BINDING_TYPE IS '绑定类型（SKILL，AGENT_NODE）';
COMMENT ON COLUMN AI_TOOL_BINDING.TOOL_ID IS '允许使用的ToolID（联合业务主键）';
COMMENT ON COLUMN AI_TOOL_BINDING.IS_DELETE IS '逻辑删除标记';
COMMENT ON COLUMN AI_TOOL_BINDING.INPUT_ID IS '创建人 ID';
COMMENT ON COLUMN AI_TOOL_BINDING.INPUT_TIME IS '创建时间';
COMMENT ON COLUMN AI_TOOL_BINDING.INPUT_ORG IS '创建机构';
COMMENT ON COLUMN AI_TOOL_BINDING.UPDATE_ID IS '最后更新人 ID';
COMMENT ON COLUMN AI_TOOL_BINDING.UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN AI_TOOL_BINDING.UPDATE_ORG IS '最后更新机构';

CREATE TABLE AI_CALL_AUDIT_LOG (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    TRACE_ID VARCHAR2(64),
    SPAN_ID VARCHAR2(32),
    CALL_TYPE VARCHAR2(10) NOT NULL,
    AGENT_ID VARCHAR2(32),
    NODE_ID VARCHAR2(32),
    CALL_NAME VARCHAR2(128) NOT NULL,
    INPUT_TEXT CLOB,
    OUTPUT_TEXT CLOB,
    SUCCESS VARCHAR2(1) NOT NULL,
    ERROR_MESSAGE CLOB,
    DURATION_MS NUMBER(20) NOT NULL,
    CREATE_TIME VARCHAR2(24) NOT NULL,
    CONSTRAINT CK_CALL_AUDIT_TYPE CHECK (CALL_TYPE IN ('MODEL', 'TOOL')),
    CONSTRAINT CK_CALL_AUDIT_SUCCESS CHECK (SUCCESS IN ('0', '1'))
);

CREATE TABLE AI_MCP_TOOL_CALL_LOG (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    TRACE_ID VARCHAR2(64),
    SPAN_ID VARCHAR2(32),
    MCP_SERVER_NAME VARCHAR2(128) NOT NULL,
    MCP_ENDPOINT VARCHAR2(256) NOT NULL,
    TOOL_NAME VARCHAR2(128) NOT NULL,
    TOOL_INPUT CLOB,
    TOOL_OUTPUT CLOB,
    SUCCESS VARCHAR2(1) NOT NULL,
    ERROR_MESSAGE CLOB,
    DURATION_MS NUMBER(20) NOT NULL,
    CREATE_TIME VARCHAR2(24) NOT NULL,
    CONSTRAINT CK_MCP_TOOL_CALL_SUCCESS CHECK (SUCCESS IN ('0', '1'))
);

CREATE TABLE AI_MCP_TOOL_CHANNEL_BLOCK (
    PK_ID VARCHAR2(32) PRIMARY KEY,
    MCP_SERVER_NAME VARCHAR2(128),
    TOOL_NAME VARCHAR2(128) NOT NULL,
    CHANNEL_CODE VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(16) NOT NULL,
    MESSAGE VARCHAR2(512),
    IS_DELETE VARCHAR2(1) NOT NULL,
    EFFECTIVE_FROM VARCHAR2(24),
    EFFECTIVE_TO VARCHAR2(24),
    CONSTRAINT CK_MCP_TOOL_CHANNEL_BLOCK_STATUS
        CHECK (STATUS IN ('ENABLED', 'DISABLED')),
    CONSTRAINT CK_MCP_TOOL_CHANNEL_BLOCK_DELETE
        CHECK (IS_DELETE IN ('0', '1')),
    CONSTRAINT UK_MCP_TOOL_CHANNEL_BLOCK
        UNIQUE (MCP_SERVER_NAME, TOOL_NAME, CHANNEL_CODE)
);

COMMENT ON TABLE AI_CALL_AUDIT_LOG IS '模型与工具调用审计日志表';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.PK_ID IS '技术主键';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.TRACE_ID IS '请求链路 ID';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.SPAN_ID IS '请求 Span ID';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.CALL_TYPE IS '调用类型：MODEL 或 TOOL';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.AGENT_ID IS 'Agent ID';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.NODE_ID IS 'Agent 节点 ID';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.CALL_NAME IS '模型 ID 或工具名称';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.INPUT_TEXT IS '完整输入原文';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.OUTPUT_TEXT IS '完整输出原文';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.SUCCESS IS '是否成功：1 成功，0 失败';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.ERROR_MESSAGE IS '异常信息';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.DURATION_MS IS '调用耗时毫秒';
COMMENT ON COLUMN AI_CALL_AUDIT_LOG.CREATE_TIME IS '审计记录创建时间';

COMMENT ON TABLE AI_MCP_TOOL_CALL_LOG IS 'MCP 工具对外调用记录表';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.PK_ID IS '技术主键';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.TRACE_ID IS '请求链路 ID';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.SPAN_ID IS '请求 Span ID';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.MCP_SERVER_NAME IS 'MCP Server 名称';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.MCP_ENDPOINT IS 'MCP Streamable HTTP 端点';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.TOOL_NAME IS 'MCP 工具名称';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.TOOL_INPUT IS '工具完整输入原文';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.TOOL_OUTPUT IS '工具完整输出原文';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.SUCCESS IS '是否成功：1 成功，0 失败';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.ERROR_MESSAGE IS '异常信息';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.DURATION_MS IS '调用耗时毫秒';
COMMENT ON COLUMN AI_MCP_TOOL_CALL_LOG.CREATE_TIME IS '记录创建时间';

COMMENT ON TABLE AI_MCP_TOOL_CHANNEL_BLOCK IS 'MCP 工具渠道禁用配置表';
COMMENT ON COLUMN AI_MCP_TOOL_CHANNEL_BLOCK.PK_ID IS '技术主键';
COMMENT ON COLUMN AI_MCP_TOOL_CHANNEL_BLOCK.MCP_SERVER_NAME IS 'MCP Server 名称，空表示全局';
COMMENT ON COLUMN AI_MCP_TOOL_CHANNEL_BLOCK.TOOL_NAME IS 'MCP 工具名称';
COMMENT ON COLUMN AI_MCP_TOOL_CHANNEL_BLOCK.CHANNEL_CODE IS '渠道编码';
COMMENT ON COLUMN AI_MCP_TOOL_CHANNEL_BLOCK.STATUS IS '状态：ENABLED 或 DISABLED';
COMMENT ON COLUMN AI_MCP_TOOL_CHANNEL_BLOCK.MESSAGE IS '禁用提示';
COMMENT ON COLUMN AI_MCP_TOOL_CHANNEL_BLOCK.IS_DELETE IS '逻辑删除标记';
COMMENT ON COLUMN AI_MCP_TOOL_CHANNEL_BLOCK.EFFECTIVE_FROM IS '生效开始时间';
COMMENT ON COLUMN AI_MCP_TOOL_CHANNEL_BLOCK.EFFECTIVE_TO IS '生效结束时间';

CREATE INDEX IDX_NODE_AGENT ON AI_AGENT_NODE (AGENT_ID);
CREATE INDEX IDX_BIND_NODE ON AI_AGENT_NODE_SKILL_BINDING (NODE_ID);
CREATE INDEX IDX_BIND_SKILL ON AI_AGENT_NODE_SKILL_BINDING (SKILL_ID);
CREATE INDEX IDX_TOOL_BINDING_TARGET ON AI_TOOL_BINDING (BINDING_TYPE, BINDING_ID);
CREATE INDEX IDX_TOOL_BINDING_TOOL ON AI_TOOL_BINDING (TOOL_ID);
CREATE INDEX IDX_CALL_AUDIT_TRACE ON AI_CALL_AUDIT_LOG (TRACE_ID);
CREATE INDEX IDX_CALL_AUDIT_TIME ON AI_CALL_AUDIT_LOG (CREATE_TIME);
CREATE INDEX IDX_MCP_TOOL_CALL_TRACE ON AI_MCP_TOOL_CALL_LOG (TRACE_ID);
CREATE INDEX IDX_MCP_TOOL_CALL_TIME ON AI_MCP_TOOL_CALL_LOG (CREATE_TIME);
CREATE INDEX IDX_MCP_TOOL_CALL_TOOL ON AI_MCP_TOOL_CALL_LOG (TOOL_NAME);
CREATE INDEX IDX_MCP_TOOL_CHANNEL_BLOCK
    ON AI_MCP_TOOL_CHANNEL_BLOCK (TOOL_NAME, CHANNEL_CODE, STATUS, IS_DELETE);
